package String.Problem2;

// Practical Question 2 (Performance Optimization – Mandatory)Problem Statement
// Build a program that constructs a dynamic message using both String and StringBuilder, and compare their behavior.
// Requirements
// Create a loop that appends numbers or words to a string
// Implement the same logic using:
// String
// StringBuilder
// Print the final result in both cases
// Expected Implementation Focus
// Use + operator for String concatenation
// Use append() for StringBuilder
// Observe object creation and performance difference
public class String1 {
    public static void main(String[] args) {
        //string
        String s="";
        String str="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
        int j=0;
        long start=System.currentTimeMillis();
        for(int i=0;i<100;i++){
            j=(int)(Math.random()*52);
            // System.out.println(j);
            s+=str.charAt(j);
        }
        long end=System.currentTimeMillis();
        System.out.println("\n\n\n");
        System.out.println("String Generated by String Concatanation required : "+ (end-start) + " ms ");
        System.out.println(s);
        System.out.println("\n\n\n");
                
        //stringbuilder
        
        StringBuilder sb=new StringBuilder();
        long startsb=System.currentTimeMillis();
        for(int i=0;i<100;i++){
            j=(int)(Math.random()*52);
            // System.out.println(j);
            sb.append(str.charAt(j));
        }
        long endsb=System.currentTimeMillis();
        System.out.println("String Generated by stringbuilder required : "+ (endsb-startsb) + " ms");
        System.out.println(sb);
    }
}
